import { NextRequest, NextResponse } from 'next/server'
import type { ExecutiveBriefResponse } from '@/app/api/executive-brief/route'

export interface GammaPromptResponse {
  prompt: string
  slideCount: number
  title: string
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json()
    const brief: ExecutiveBriefResponse = body.brief

    if (!brief?.executiveSummary && !brief?.summary) {
      return NextResponse.json({ error: 'Executive brief data is required' }, { status: 400 })
    }

    const summary = brief.executiveSummary || brief.summary
    const generatedDate = brief.generatedAt
      ? new Date(brief.generatedAt).toLocaleDateString('en-AE', {
          timeZone: 'Asia/Dubai',
          day: 'numeric',
          month: 'long',
          year: 'numeric',
        })
      : 'April 2026'

    const ratingLabel =
      brief.riskRating === 'critical' ? 'CRITICAL RISK'
      : brief.riskRating === 'elevated' ? 'ELEVATED RISK'
      : brief.riskRating === 'moderate' ? 'MODERATE RISK'
      : 'CURRENT RISK POSTURE'

    const topRisksText = (brief.topRisks || [])
      .slice(0, 5)
      .map((r) => `• ${r.title} — ${r.portfolio} — ${r.financialImpact} (${r.urgency})`)
      .join('\n')

    const actionsText = (brief.recommendedActions || [])
      .slice(0, 5)
      .map((a) => `• ${a.action} | Owner: ${a.owner} | ${a.deadline}`)
      .join('\n')

    const implText = (brief.strategicImplications || [])
      .map((s) => `• ${s}`)
      .join('\n')

    const metrics = brief.keyMetrics
    const metricsText = metrics
      ? [
          `• Overall Risk Score: ${metrics.overallRiskScore}/100`,
          `• Financial Exposure: AED ${metrics.financialExposureAED}M`,
          `• Critical Risks: ${metrics.criticalRisks}`,
          `• Risks Requiring Board Attention: ${metrics.risksRequiringBoardAttention}`,
        ].join('\n')
      : ''

    const sourcesText = (brief.sourceReferences || [])
      .map((s) => `• ${s.source}: ${s.detail}`)
      .join('\n')

    const prompt = `Create a premium board presentation with the following content. Use a dark executive theme — deep navy or black background, white text, gold or teal accent colour. Clean, modern consulting aesthetic. Minimal text per slide, high visual impact.

---

Title: Aldar Properties PJSC
Subtitle: Enterprise Risk Intelligence Brief
Date: ${generatedDate}
Classification: Board Confidential

---

Slide 1 — Executive Summary
Heading: Executive Risk Summary
Risk Status: ${ratingLabel}
Confidence: ${Math.round((brief.confidence || 0.85) * 100)}%

${summary}

Key Metrics:
${metricsText}

---

Slide 2 — Key Risks
Heading: Top Risks — Board Attention Required

${topRisksText}

Style note: Use a risk severity table or coloured risk cards. Highlight "immediate" urgency items in red.

---

Slide 3 — Business Impact
Heading: Financial & Operational Impact

${brief.businessImpact || 'Cross-portfolio financial and operational impact assessment.'}

Market Context:
${brief.marketContext || ''}

---

Slide 4 — Cross-Portfolio Impact
Heading: Cross-Portfolio Risk Propagation

${brief.crossPortfolioImpact || 'Risk propagation analysis across Aldar business units.'}

Strategic Implications:
${implText}

Style note: Use a flow diagram or connected card layout showing how risks move across BUs.

---

Slide 5 — Recommended Actions
Heading: Board-Recommended Actions

${actionsText}

Style note: Number each action. Use a priority matrix or timeline layout. Show ownership clearly.

---

Slide 6 — Sources & Confidence
Heading: Data Sources & Traceability
Subheading: This brief was generated by Aldar AI Risk & Control Operating System

Data Sources:
${sourcesText || '• Aldar Risk Register (15 active risks)\n• Oracle Fusion ERP (Q2 2026)\n• AI Fusion Engine (cross-signal analysis)'}

Note: All content generated by AI Risk Intelligence Engine. Reviewed and validated before board submission.
Confidence level: ${Math.round((brief.confidence || 0.85) * 100)}%

---

Design guidelines:
- Theme: Dark premium consulting (black/navy, gold or electric blue accents)
- Font: Clean sans-serif (e.g. Inter, Helvetica)
- Each slide: one clear heading, concise bullets, no paragraphs longer than 2 lines
- Slide 4: include a simple risk propagation flow diagram
- Slide 5: use a styled action table with columns: Priority, Action, Owner, Deadline
- Brand: Include "Aldar Properties PJSC" in footer of every slide
- Tone: Board-level, authoritative, data-driven`

    return NextResponse.json({
      prompt,
      slideCount: 6,
      title: 'Aldar Risk Intelligence Brief — Board Presentation',
    } satisfies GammaPromptResponse)
  } catch (error: unknown) {
    const msg = error instanceof Error ? error.message : 'Unknown error'
    console.error('Gamma prompt error:', msg)
    return NextResponse.json({ error: `Failed to generate Gamma prompt: ${msg}` }, { status: 500 })
  }
}
